version: '3.6'

services:
  flask_api:
    build:
      context: .
      dockerfile: Dockerfile
    image:  flask:kika

    container_name: flaskapi
    ports:
      - 5000:5000
    networks:
      - flaskapi


  minio:
      image: minio/minio:RELEASE.2020-04-10T03-34-42Z

      container_name: minio
      volumes:
        - /minio-data:/data
      ports:
        - '9000:9000'
      networks:
        - flaskapi

      environment:
        - MINIO_ACCESS_KEY=minio
        - MINIO_SECRET_KEY=minio123
      command: server  /data

networks:
  flaskapi:
#    driver: bridge

volumes:
  db: